dataset: "airfoil"
regression: True
prior_size: 0.0
validation_size: 0.1
test_size: 0.1
max_epochs: 1
batch_size: 64


# bound parameters
delta: 0.01
nbr_parameter_bounds: 20
classic_bounds: False
p2l_bounds: False
real_bounds: True

# miscellaneous
n_jobs: 5
warm_start: False
log_iterations: 2
deterministic: True
clamping: True
early_stopping: True
early_stopping_patience: 20
min_val: 99
max_val: 145