dataset: "amazon"
n_classes: 2
regression: False
prior_size: 0.0
validation_size: 0.1
test_size: 0.1
max_epochs: 200
batch_size: 128


# bound parameters
delta: 0.01
nbr_parameter_bounds: 20
classic_bounds: True
p2l_bounds: True
real_bounds: True

# miscellaneous
warm_start: False
log_iterations: 10
deterministic: True
clamping: True
early_stopping: False
early_stopping_patience: 10
min_probability: 1e-5
n_shards: 10