dataset: "cifar10"
n_classes: 2
first_class: [0, 1, 2, 3, 5]
second_class: [8, 9, 6, 4, 7]
validation_size: 0.1
max_epochs: 200
batch_size: 64

# bound parameters
delta: 0.01
nbr_parameter_bounds: 20
classic_bounds: True
p2l_bounds: True
real_bounds: True

# miscellaneous
log_iterations: 10
deterministic: True