dataset: "rice"
regression: False
n_classes: 2
first_class: None #[0, 1, 2, 4, 5, -1]
second_class: None #[8, 7, 3, 9, 6, -1]
validation_size: 0.1
test_size: 0.1
max_epochs: 200
batch_size: 64

# bound parameters
delta: 0.01
nbr_parameter_bounds: 20
classic_bounds: True
p2l_bounds: True
real_bounds: True

# miscellaneous
log_iterations: 10
deterministic: True
clamping: True
early_stopping: False
early_stopping_patience: 20
min_probability: 1e-5
