name: sweep
method: grid
metric:
  goal: minimize
  name: validation_loss
  
parameters:
  # pretraining details
  prior_size:
    value: 0.0
  pretraining_epochs:
    value: None
  pretraining_lr:
    value: None

  # training details
  model_type:
    value : "mlp"
  dropout_probability:
    values: [0.1, 0.2]

  # optimizer
  optimizer:
    values: ["Adam"]
  training_lr:
    values: [1e-3, 1e-4]
  momentum:
    value: 0.95
  nesterov:
    value: True

  # p2l params
  max_compression_size:
    value: -1
  data_groupsize: 
    values: [1]
  patience:
    values: [3]