name: sweep
method: grid
metric:
  goal: minimize
  name: kl_bound
  
parameters:
  seed:
    values: [1, 2, 3, 4, 42]
  model_type:
    value: forest
  max_depth:
    values: [5, 10]
  min_samples_split:
    values: [2, 3, 4]
  min_samples_leaf:
    values: [1, 2, 3]
  n_estimators:
    values: [50, 100]
  ccp_alpha:
    values: [0.0, 0.05, 0.1, 0.2, 0.5, 1, 2]
  n_add_estimators:
    value: None

# p2l params
  max_compression_size:
    value: -1
  data_groupsize: 
    value: 1
  patience:
    value: 1