name: sweep
method: grid
metric:
  goal: minimize
  name: kl_bound
  
parameters:
  seed:
    values: [1, 2, 3, 4, 42]
  # pretraining details
  prior_size:
    value: 0.0
  pretraining_epochs:
    value: None
  pretraining_lr:
    value: None
  max_epochs:
    value: 1
  

  # training details
  model_type:
    value : "mlp"

  # optimizer
  optimizer:
    value: "Adam"
  training_lr:
    values: [1e-2, 1e-3, 5e-3, 1e-4]
  momentum:
    value: None
  nesterov:
    value: None

  # p2l params
  max_compression_size:
    value: 2000
  data_groupsize: 
    values: [2,4, 8, 16, 32, 64]
  patience:
    value: 3