name: sweep
method: grid
metric:
  goal: minimize
  name: kl_bound
  
parameters:
  # pretraining details
  prior_size:
    value: 0.2
  pretraining_epochs:
    values: [50, 100]
  pretraining_lr:
    values: [1e-2, 1e-3, 1e-4]

  # training details
  model_type:
    value : "cnn"
  dropout_probability:
    values: [0.1, 0.2]

  # optimizer
  optimizer:
    value: "Adam"
  training_lr:
    values: [1e-3, 5e-3, 1e-4]
  momentum:
    value: None
  nesterov:
    value: None

  # p2l params
  max_compression_size:
    value: 1000
  data_groupsize: 
    value: [1, 32]
  patience:
    values: [3, 5] 