name: sweep
method: grid
metric:
  goal: minimize
  name: kl_bound
  
parameters:
  seed:
    values: [1, 2, 3, 4, 42]
  # pretraining details
  prior_size:
    value: 0.5
  pretraining_epochs:
    values: [20, 50]
  pretraining_lr:
    value: 1e-3

  # training details
  model_type:
    value : "transformer"
  dropout_probability:
    values: [0.1, 0.2]

  # optimizer
  optimizer:
    value: "Adam"
  training_lr:
    values: [1e-4, 1e-5, 1e-6]
  momentum:
    value: None
  nesterov:
    value: None

  # p2l params
  max_compression_size:
    value: 20000
  data_groupsize: 
    value: 32
  patience:
    value: 3